#!/usr/bin/env python

import os

Import('envGlobal')

# As other sibling repos may already contain GTest
if not 'GTEST_EXISTS' in envGlobal:
    envGlobal['GTEST_EXISTS'] = 1
    envGlobal.Append(CCFLAGS=('-isystem', os.path.abspath('..')))

    env = envGlobal.Clone()
    env['CCFLAGS_warning'] = []

    files = ['gtest-all.cc', 'gtest_main.cc']

    library = env.StaticLibrary('gtest', files)
    envGlobal.Install('../lib', library)

